# Generated by Django 6.0.5 on 2026-06-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('ID_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=20, verbose_name='Nombres*')),
                ('Telefono', models.CharField(max_length=12, verbose_name='Teléfono*')),
                ('Correo', models.EmailField(max_length=254, verbose_name='Correo*')),
                ('Fecha_Registro', models.DateField(verbose_name='Fecha Registro*')),
                ('Origen', models.CharField(max_length=50, verbose_name='Origen*')),
                ('Interes', models.CharField(max_length=150, verbose_name='Interes*')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
